version: '3'

services:
  collector:
    build: .
    ports:
      - "5000:5000"
    networks:
      - ne2_nids
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: collector
      MYSQL_USER: ne2_admin
      MYSQL_PASSWORD: appelflap
      MYSQL_ROOT_PASSWORD: appelflap
    volumes:
      - ./collector/mysql:/docker-entrypoint-initdb.d
    networks:
      ne2_nids:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_USER: ne2_admin
      MYSQL_PASSWORD: appelflap
      MYSQL_ROOT_PASSWORD: appelflap
    networks:
      - ne2_nids

networks:
  ne2_nids: