version: '3.7'

services:
  collector:
    build: .
    ports:
      - "5000:5000"

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: collector
      MYSQL_USER: ne2_admin
      MYSQL_PASSWORD: appelflap
      MYSQL_ROOT_PASSWORD: appelflap
    volumes:
      - ./collector/mysql:/docker-entrypoint-initdb.d
    links:
      - collector:collector

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_USER: ne2_admin
      MYSQL_PASSWORD: appelflap
      MYSQL_ROOT_PASSWORD: appelflap